// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import PlaybookContent from "./playbook-content";

export const metadata: Metadata = {
  title: "Everyday HR Playbook — HR Playhouse Hub",
  description: "",
};

export default function Page() {
  return <PlaybookContent />;
}
