// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import ResourcesContent from "./resources-content";

export const metadata: Metadata = {
  title: "Resources Library — HR Playhouse Hub",
  description: "",
};

export default function Page() {
  return <ResourcesContent />;
}
