// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import HomeContent from "./home-content";

export const metadata: Metadata = {
  title: "The HR Playhouse Hub — Where HR Professionals Grow",
  description: "HR Playhouse Hub is a learning platform unlike any other — research-backed, gamified, story-driven HR development from your first role to the executive table.",
};

export default function Page() {
  return <HomeContent />;
}
