// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import EmailSenderContent from "./email-sender-content";

export const metadata: Metadata = {
  title: "HR Playhouse Hub — Email Sender",
  description: "",
};

export default function Page() {
  return <EmailSenderContent />;
}
