/**
 * HTML -> Next.js page generator (faithful port).
 *
 * For each HTML file listed in route-map.mjs this script:
 *   1. Parses the document with node-html-parser.
 *   2. Extracts <title>/<meta name="description"> into a Next.js `metadata` export.
 *   3. Extracts every <style> block into a colocated `<route>.css` file.
 *   4. Extracts the <body> inner HTML and renders it via dangerouslySetInnerHTML
 *      so the original markup AND its 385 inline event handlers keep working
 *      exactly as they did on the WordPress site.
 *   5. Extracts every <script> and re-emits it through next/script so the
 *      page's own JS runs after the markup is in the DOM.
 *   6. Rewrites cross-page ".html" links to Next.js routes.
 *
 * This is a deliberate faithful-port strategy: pixel- and behaviour-identical
 * to the originals, regeneratable any time the source HTML changes.
 *
 * Usage:  node scripts/generate-pages.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "node-html-parser";
import { ROUTE_MAP, LINK_REWRITES, LMS_PATH_MAP } from "./route-map.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SRC_DIR = join(ROOT, "Corrected Files for HRPH");
const APP_DIR = join(ROOT, "src", "app");
const GEN_MARKER = "// @generated by scripts/generate-pages.mjs — do not edit by hand";

/** Rewrite cross-page .html links and absolute WP URLs to Next.js routes. */
function rewriteLinks(html) {
  let out = html;
  for (const { from, to } of LINK_REWRITES) {
    // Replace href="...from..." preserving any ?query or #hash suffix.
    const escaped = from.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const re = new RegExp(`(href=")${escaped}((?:[?#][^"]*)?")`, "g");
    out = out.replace(re, `$1${to}$2`);
  }
  // LMS subdomain links -> internal routes, but only for the paths we have
  // a local equivalent for. e.g.
  //   https://learn.thehrplayhousehub.org/case-study-vault/  ->  /case-study-vault
  out = out.replace(
    /https?:\/\/learn\.thehrplayhousehub\.org\/([a-z0-9-]+)\/?/g,
    (match, path) => LMS_PATH_MAP[path] ?? match,
  );
  // Absolute links to the marketing site root -> internal home.
  // (Only the bare root and root-relative file links; deeper marketing
  // pages, if any, are left untouched.)
  out = out.replace(
    /https?:\/\/(?:www\.)?thehrplayhousehub\.org\//g,
    "/",
  );
  return out;
}

/** Turn a JS string into a safe single-quoted JS literal for embedding. */
function jsString(s) {
  return JSON.stringify(s);
}

function generateOne({ html, route }) {
  const srcPath = join(SRC_DIR, html);
  if (!existsSync(srcPath)) {
    console.warn(`  ! skip (missing): ${html}`);
    return null;
  }

  const isHomeCheck = route === "";
  const isNotFoundCheck = route === "__not_found__";
  const outDirCheck = isHomeCheck
    ? APP_DIR
    : isNotFoundCheck
      ? APP_DIR
      : join(APP_DIR, route);
  const slugCheck = isHomeCheck ? "home" : isNotFoundCheck ? "not-found" : route;
  const contentFileCheck = `${slugCheck}-content.tsx`;
  const contentPath = join(outDirCheck, contentFileCheck);
  if (existsSync(contentPath)) {
    const firstLine = readFileSync(contentPath, "utf8").split("\n")[0] ?? "";
    if (!firstLine.startsWith(GEN_MARKER)) {
      console.warn(`  ! skip (hand-edited, marker missing): ${html} -> /${route}`);
      return { route: isHomeCheck ? "/" : isNotFoundCheck ? "(404)" : `/${route}`, outDir: outDirCheck, skipped: true };
    }
  }
  const raw = readFileSync(srcPath, "utf8");
  const doc = parse(raw, {
    comment: true,
    blockTextElements: { script: true, style: true },
  });

  // --- metadata ---
  const title =
    doc.querySelector("title")?.text?.trim() || "The HR Playhouse Hub";
  const description =
    doc.querySelector('meta[name="description"]')?.getAttribute("content") ||
    "";

  // --- styles -> colocated css ---
  const styles = doc
    .querySelectorAll("style")
    .map((n) => n.text)
    .join("\n\n");

  // --- scripts: split inline vs external (e.g. EmailJS CDN) ---
  const scripts = doc.querySelectorAll("script");
  const externalSrcs = [];
  const inlineCode = [];
  for (const s of scripts) {
    const src = s.getAttribute("src");
    if (src) externalSrcs.push(src);
    else if (s.text.trim()) inlineCode.push(s.text);
  }

  // --- body inner html (links rewritten) ---
  const body = doc.querySelector("body");
  let bodyHtml = body ? body.innerHTML : doc.toString();
  bodyHtml = rewriteLinks(bodyHtml);

  const isNotFound = route === "__not_found__";
  const isHome = route === "";
  const slug = isHome ? "home" : route;
  const cssName = isNotFound ? "not-found.css" : `${slug}.css`;
  const baseName = route
    ? route
        .split(/[-_/]/)
        .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
        .join("")
    : "Home";
  const clientComponent = `${isNotFound ? "NotFound" : baseName}Content`;

  // Target directory: app/ (home & not-found) or app/<route>/
  const outDir = isHome || isNotFound ? APP_DIR : join(APP_DIR, route);
  mkdirSync(outDir, { recursive: true });

  // Write the colocated stylesheet.
  if (styles.trim()) {
    writeFileSync(join(outDir, cssName), `${styles}\n`, "utf8");
  }

  // Build the script tags. External first (e.g. EmailJS), then inline.
  const idBase = isNotFound ? "notfound" : slug;
  const externalTags = externalSrcs
    .map(
      (src, i) =>
        `      <Script src=${jsString(src)} strategy="afterInteractive" id="ext-${idBase}-${i}" />`,
    )
    .join("\n");
  const inlineTags = inlineCode
    .map(
      (code, i) =>
        `      <Script id="inline-${idBase}-${i}" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: ${jsString(code)} }} />`,
    )
    .join("\n");

  const cssImport = styles.trim() ? `import "./${cssName}";\n` : "";
  const needScript = externalSrcs.length || inlineCode.length;

  // --- 1. Client component: the actual markup + the page's own JS ---
  const contentFile = `${isNotFound ? "not-found-content" : `${slug}-content`}.tsx`;
  const contentTsx = `${GEN_MARKER}
"use client";
${needScript ? '\nimport Script from "next/script";' : ""}
${cssImport}
export default function ${clientComponent}() {
  return (
    <>
      <div dangerouslySetInnerHTML={{ __html: ${jsString(bodyHtml)} }} />
${externalTags}
${inlineTags}
    </>
  );
}
`;
  writeFileSync(join(outDir, contentFile), contentTsx, "utf8");

  // --- 2. Server component: metadata + renders the client component ---
  // not-found.tsx does not support a metadata export, so it just re-exports.
  const entryName = isNotFound ? "not-found.tsx" : "page.tsx";
  let entryTsx;
  if (isNotFound) {
    entryTsx = `${GEN_MARKER}
import ${clientComponent} from "./${contentFile.replace(/\.tsx$/, "")}";

export default function NotFound() {
  return <${clientComponent} />;
}
`;
  } else {
    entryTsx = `${GEN_MARKER}
import type { Metadata } from "next";
import ${clientComponent} from "./${contentFile.replace(/\.tsx$/, "")}";

export const metadata: Metadata = {
  title: ${jsString(title)},
  description: ${jsString(description)},
};

export default function Page() {
  return <${clientComponent} />;
}
`;
  }
  writeFileSync(join(outDir, entryName), entryTsx, "utf8");

  return { route: isHome ? "/" : isNotFound ? "(404)" : `/${route}`, outDir };
}

console.log(`Generating ${ROUTE_MAP.length} pages from "${SRC_DIR}"\n`);
const results = [];
for (const entry of ROUTE_MAP) {
  const r = generateOne(entry);
  if (r) {
    console.log(`  ✓ ${entry.html.padEnd(32)} -> ${r.route}`);
    results.push(r);
  }
}
console.log(`\nDone. ${results.length}/${ROUTE_MAP.length} pages generated.`);
