// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import InnovationLabContent from "./innovation-lab-content";

export const metadata: Metadata = {
  title: "Virtual Innovation Lab — HR Playhouse Hub",
  description: "The Virtual Innovation Lab — collaborate on real-world HR challenges, submit ideas, get feedback, and connect with mentors.",
};

export default function Page() {
  return <InnovationLabContent />;
}
