// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import AiSupportContent from "./ai-support-content";

export const metadata: Metadata = {
  title: "AI HR Support — HR Playhouse Hub",
  description: "Get instant, research-backed answers to your HR questions. Upload documents for AI-powered analysis.",
};

export default function Page() {
  return <AiSupportContent />;
}
