// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import PricingContent from "./pricing-content";

export const metadata: Metadata = {
  title: "Pricing — HR Playhouse Hub",
  description: "",
};

export default function Page() {
  return <PricingContent />;
}
