// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import WebinarBookingContent from "./webinar-booking-content";

export const metadata: Metadata = {
  title: "Webinar Booking — HR Playhouse Hub",
  description: "Register for free live HR webinars hosted by Dr. Marvellous Gberevbie. Sessions on culture, performance, AI in HR and more.",
};

export default function Page() {
  return <WebinarBookingContent />;
}
