// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import CaseStudyVaultContent from "./case-study-vault-content";

export const metadata: Metadata = {
  title: "Case Study Vault — HR Playhouse Hub",
  description: "",
};

export default function Page() {
  return <CaseStudyVaultContent />;
}
