// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import MyCoursesContent from "./my-courses-content";

export const metadata: Metadata = {
  title: "My Courses — HR Playhouse Hub",
  description: "",
};

export default function Page() {
  return <MyCoursesContent />;
}
