// @generated by scripts/generate-pages.mjs — do not edit by hand
import type { Metadata } from "next";
import DashboardContent from "./dashboard-content";

export const metadata: Metadata = {
  title: "My Dashboard — HR Playhouse Hub",
  description: "",
};

export default function Page() {
  return <DashboardContent />;
}
